### PR TITLE
Homework 1

### PR DESCRIPTION
**Pull request by woowenjun99**
Homework completed, left comments in readme.md file. Created ipynb file to assist me with homework but it is gibberish so ignore it. Main file is the original python file

### CODE REVIEW

**Review by syoopie — CHANGES_REQUESTED** [review]
Your python file cannot be run and from a rough look has many indentation errors. Please relook and fix

**Comment by woowenjun99** [comment]
Completed Homework 1 second round

**Comment by codecodecoder78** [comment]
Your output is 

successfulApplicants : ['Amy']
bannedApplicants : ['Amy']
totalCost : 2.0

tickers: [

name : Amy
membershipStatus : False
price : 5.0

name : Ally
membershipStatus : False
price : 3.5
membership : True

name : David
membershipStatus : False
price : 3.5
membership : True

]

Successful applicants is wrong

**Comment by codecodecoder78** [comment]
Also instructions are to return a python dict with the details, not print to console

**Pull request closed without merging**
